### ISSUE TITLE
interact with SMT solver

### ISSUE THREAD

**Issue by Smattr** [Smattr/rumur#130]
One way of implementing #13 would be to ask an SMT solver if two rules satisfy the necessary POR side conditions. For this, we'll first have to teach Rumur how to speak to an SMT solver. A good preliminary step would be implementing some type of DCE using this.

**Comment by Smattr** [comment]
@yurivict, I'm intending to merge the feature/smt-solver branch in the next few days that contains commits related to this issue. 20794d63f36d069e23c2962b13167e971d163d0d adds a Python script that the test suite ends up causing Rumur to call as `python <path>/misc/toy-smt.py ...`. I think it may cause shebangfix-related problems for the FreeBSD package. Is it simpler for you if I `chmod +x` this script, call it as `<path>/misc/toy-smt.py ...` and let you shebangfix-patch its shebang?

**Comment by Smattr** [comment]
This is essentially done. What is required for #13 is some evolution of the SMT bridge to get it to understand aggregate types (arrays and records) and the effect of statements/functions. The latter will probably require some internal implementation of [SSA](https://en.wikipedia.org/wiki/Static_single_assignment_form).

For posterity, the previous comment is no longer relevant because the toy SMT solver was removed in 81d412356ceb739e20d28324f817e61ac8d48708 and the test suite now simply calls Z3 or CVC4 if they're available.

**Comment by yurivict** [comment]
Thanks for warning me about shebangs!
I'll handle them. -)
