### ISSUE TITLE
fails to build on Fedora 30

### ISSUE THREAD

**Issue by Smattr** [Smattr/rumur#146]
As reported by @jreiser on https://github.com/upx/upx/issues/297.

> rumur does not build. I changed the beginning of CMakeLists.txt to
>
> ```
> # cmake_minimum_required(VERSION 3.1)
> cmake_minimum_required(VERSION 3.14)
>
> project(rumur LANGUAGES CXX)
> install(PROGRAMS rumur DESTINATION /usr/local/bin)
> ```
> but still got
> ```
> $ cmake --version   # in Fedora 30
> cmake version 3.14.5
> $ cmake ../rumur
> CMake Error at CMakeLists.txt:93 (install):
>   install PROGRAMS given no DESTINATION!
>
>
> CMake Warning (dev) in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
>
>     cmake_minimum_required(VERSION 3.14)
> ```

**Comment by Smattr** [comment]
I tried to reproduce this in an x86-64 Fedora 30 virtual machine, but midway through I realised what the problem is. The rumur/CMakeLists.txt file is not intended to be used standalone. Rumur should be buildable out of the box on a fresh Fedora 30 with the following steps:

```sh
# install dependencies
$ sudo dnf install g++ make cmake gmp-devel bison flex python

# download Rumur
$ git clone https://github.com/smattr/rumur

# configure and compile
$ mkdir rumur/build
$ cd rumur/build
$ cmake ..
$ make
```

@jreiser please let me know if these steps don't work for you.

**Comment by Smattr** [comment]
Argh now I see where the confusion stems from: the README is wrong. Apologies. I will correct this now.

**Comment by Smattr** [comment]
Actually, no, it is not. It is describing a directory structure like:

```
~/
|
+- build/
+- rumur/
```

Sorry for yet more churn on this issue, but it looks like there was no problem originally.

**Comment by jreiser** [comment]
Thank you for prompt investigation.  However, I believe there still is a problem with the developer interface in README.rst:
```
    # Download Rumur
    git clone https://github.com/Smattr/rumur   # Create top-level rumur directory

    # Configure and compile
    mkdir build   # This should be inside the top-level rumur directory, not a sibling.
    cd build
    cmake ../rumur   # adjust the path
    make
    make install
```
It is not nice for the `build` directory to be outside of the top-level `rumur` directory that is created by the `git clone`.  That collides with developer use of the directory that contains the top-level `rumur` directory, which in my case contains `many` projects, each in its own subtree.    The assumption that rumur can use a sibling directory (in the case, named `build`) pollutes the namespace of the directory that contains each project in its own subdirectory. Use only child directories.  This practice is so automatic that "on autopilot" I did `cd rumur` before the `mkdir build`.  It did not help that cmake error messages are not developer friendly: the complete rooted pathname is not given, so a cmake error in a source tree that has multiple CMakeLists.txt files often leads to confusion.   (A better way: if there are `any` pathnames that involve multiple directories [contain any `/`], then use readlink() to get an absolute pathname.  Perhaps punctuate: `[/absolute/path/to/]dir1/file2`.)

**Comment by Smattr** [comment]
This is a personal preference, however I have no strong feelings on the matter so I've rephrased the README to fit the work flow you describe.
