### ISSUE TITLE
uncensored cpu/ram usage

### ISSUE THREAD

**Issue by mator** [Smattr/rumur#183]
Hello!

Filed a debian bug yesterday, can you please have a look?! 

https://bugs.debian.org/951497

Thanks.

**Comment by Smattr** [comment]
> probably fixed with 1e8c9ab
 
Partially. Debian packaging is done on the packaging/debian branch, so I need to commit some things there that apply this to the upcoming v2020.02.17-1 as well as a v2020.01.17-2.
