### ISSUE TITLE
Tests freeze for 

### ISSUE THREAD

**Issue by yurivict** [Smattr/rumur#196]
```cmake --build . --target check``` hangs:

```
===>  Testing for rumur-2020.06.20
[1/51] cd /usr/ports/math/rumur/work/.build/librumur && /usr/bin/env true
```

**Comment by Smattr** [comment]
Hi Yuri, sorry the test suite doesn't seem to be running correctly. Unfortunately I can't seem to reproduce this:

```sh
$ uname -rms
FreeBSD 12.1-RELEASE amd64
$ git clone https://github.com/smattr/rumur -b v2020.06.20
...
$ cd rumur
$ mkdir build
$ cd build
$ cmake ..
...
$ cmake --build .
...
$ cmake --build . --target check
...
2680 passed, 1865 skipped, 0 failed out of 4545 total tests
[100%] Built target check
```

I'm a little confused by the output you've quoted. Is this from some wrapper script? I don't believe the Rumur test suite calls `true` anywhere.

**Comment by yurivict** [comment]
It just silently compiles for a very long time.

Sorry for bothering you.

**Comment by Smattr** [comment]
Ah yes, the test suite takes quite a long time to run now. However, it should generate output while it's running. E.g. the CI output from that release on FreeBSD 12.1: https://cirrus-ci.com/task/4876235564122112.

**Comment by yurivict** [comment]
Yes, it generates output later, when tests run.
